create two new lists height and weight 

In [8]:
import numpy as np

In [10]:
height = [1.87, 1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]


np_height = np.array(height)
np_weight = np.array(weight)

print(np_height)


[1.87 1.87 1.82 1.91 1.9  1.85]


calculate BMI

In [14]:
#calculate BMI 
bmi = np_weight / np_height ** 2
#print result 
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


print only observations above 23

In [15]:
bmi[bmi > 23]

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])